# name: Node.js CI

# on: 
#   push:
#     branches: [ main ]

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [16.x, 18.x, 20.x]
      
#     steps:
#      - name: Checkout code
#        uses: actions/checkout@v4

#      - name: Set up nodejs
#        uses: actions/setup-node@v4
#        with:
#          node-version: ${{ matrix.node-version }}
#          cache: 'npm'

#      - name: Install dependencies
#        run: npm ci

#      - name: Run tests
#        run: npm test 