name: Artifact and Deploy

on: 
  push:
    branches: [ main ]

permissions: 
  contents: read
  id-token: write
  pages: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build 
        run: |
          mkdir -p build
          echo "<h1>Deployed from Actions!</h1>" > build/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy1.outputs.page_url }}

    steps:
      - name: Download artifact
        id: deploy1
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
