# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Grant the GITHUB_TOKEN permissions to write to the deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # In a real app, this step would be 'npm run build' or similar
      - name: Simulate a build step
        run: |
          mkdir -p build
          echo "<h1>Deployed from Actions!</h1>" > build/index.html

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-artifact
          path: ./build

  deploy:
    # This job depends on the 'build' job completing successfully
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # The artifact name must match the one from the 'build' job
        with:
          artifact_name: github-pages-artifact
